### ISSUE TITLE
ZPM Field Generator does not require Soldering Alloy

### ISSUE THREAD

**Issue by ChaosBeing** [Nomi-CEu/nomi-ceu#366] opened 2023-05-24 07:23 UTC
### Nomi CEu Version

1.6.1-beta-2

### Launcher

FTB App

### Environment

Singleplayer

### Mode

Normal Mode

### What Happened

Title. The recipe in HEI shows liquid Soldering Alloy as part of the recipe, but it is not needed.

### Expected Behavior

The Assembly Line should probably consume the soldering alloy, unless the displayed recipe is wrong.

### Reproduction Steps

Set up an Assembly and try to craft it.

**Comment by Folanlron** [comment] 2023-05-24 07:24
Discord Link, https://discord.com/channels/927050775073534012/954620685848825886/1110828154123198484

**Comment by IntegerLimit** [comment] 2023-05-25 11:33
Hmm... weird... my first instinct would be launcher, but thats fine. Not sure... usually scripts don't bug out, but I'll have a look.

**Comment by IntegerLimit** [comment] 2023-05-25 11:35
Recipe in script found https://github.com/Nomi-CEu/nomi-ceu/blob/main/overrides/scripts/Endgame.zs#L219-L228.

**Comment by IntegerLimit** [comment] 2023-05-25 11:43
Cannot reproduce. Try using a different launcher, re-installing the pack, especially if you were using the `Update Pack` Functionality.

**Comment by IntegerLimit** [comment] 2023-05-25 11:43
Closed as cannot reproduce.

**Closed by IntegerLimit** 2023-05-25 11:43 UTC
Labels: bug
