### ISSUE TITLE
Crash with Sponge Forge

### ISSUE THREAD

**Issue by MojangPlsFix** [Nomi-CEu/Nomi-CEu#968] opened 2024-08-27 18:37 UTC
### Nomi CEu Version

1.7

### Launcher

Server: Alpine Linux and Windows

### Configurations or Mods Changed

- `threadPriorityFix` to false in `loliasm.cfg`
-  Remove VintageFix Mod
-  Set `B:"Entity Tracker"` to false in `Universal Tweaks - Bugfixes.cfg`

### Environment

Serverpack + SpongeForge
Forge:  14.23.5.2860
SpongeForge: 7.4.8-RC4142 and 7.4.7

### Mode

Both Modes

### What Happened

Server crashes in the early Stage due to some conflict with NomiLabs and SpongeForge. See Logs for more info.
Crash does not occur when removing the mod.

### Expected Behavior

No Crash

### Reproduction Steps

1. Download Serverpack
2. Add SpongeForge
3. Crash

### Logs

[latest.log](https://github.com/user-attachments/files/16767364/latest.log)

**Comment by IntegerLimit** [comment] 2024-08-29 11:54
Did the pack ever work with SpongeForge? Do you mean removing Nomi Labs fixing the crash, or removing SpongeForge fixing the crash? If you meant removing SpongeForge, does removing Nomi Labs fix the crash?

**Comment by MojangPlsFix** [comment] 2024-08-29 12:44
> Did the pack ever work with SpongeForge? Do you mean removing Nomi Labs fixing the crash, or removing SpongeForge fixing the crash? If you meant removing SpongeForge, does removing Nomi Labs fix the crash?

We got the pack running in 1.6.X with a Bansoukou fix of GregTechCEu/GregTech#2043, using the fixed version of MixinBooter: CleanroomMC/MixinBooter#34 and we needed to disable `threadPriorityFix` in loliASM/censoredASM, which we will have to do in 1.7 as well.

In the updated/added Mods every Mod seems to be compatible with SpongeForge, since some other Modpacks use them, except Gregtech/Nomi-related ones.
I tested the most updated/added Mod in this release if it could cause the crash. The only case, where I removed Mod that did not lead to the crash reported was NomiLabs.

**Comment by MojangPlsFix** [comment] 2024-08-29 14:47
Updated the Configuration Description of the issue. This makes the server start until a NC Recipe is registered, since the fix of NomiLabs is removed.

**Comment by IntegerLimit** [comment] 2024-08-29 22:13
I see, thank you for the detail! Investigating now.

**Comment by MojangPlsFix** [comment] 2024-08-30 06:25
Regarding removing VintageFix. We do not run into a crash when using the latest version(0.5.1). This was just tested with SpongeForge and VintageFix.

**Comment by IntegerLimit** [comment] 2024-08-30 06:58
Ok, thanks, I will update to latest for the update. However, the UT and LoliASM Configs will most likely not be changed. (maybe UT, but definitely not LoliASM)

**Comment by MojangPlsFix** [comment] 2024-08-30 07:20
> Ok, thanks, I will update to latest for the update. However, the UT and LoliASM Configs will most likely not be changed. (maybe UT, but not LoliASM)

SpongeForge-specific configs(that will probably reduce Performance) are not needed. A disclaimer/tutorial in the GitHub Repo would be nice.  I can make a PR for that when Nomi runs on Sponge again.

**Comment by IntegerLimit** [comment] 2024-08-30 10:25
I've fixed it in Labs! However, I have noticed that some of our Groovy Scripts aren't running correctly, seemingly due to obfuscation issues.

Might be a GroovyScript issue, should report there if you can reproduce in a isolated environment. (seems to be due to `EnumDyeColor.getMetadata()`, `ItemStack.getMetadata()`, and `IFrameable.decorate` (Storage Drawers 5.5.0 Method)

When I update Labs in Nomi-CEu, I'll close this issue, as the game will no longer be unrunnable.

If you are available, before I release Labs, can you check that [This Labs Build](https://github.com/Nomi-CEu/Nomi-Labs/actions/runs/10631026525) fixes the crash?

**Comment by IntegerLimit** [comment] 2024-08-30 12:53
I've released labs (but not updated it here yet), to test it, just update your Nomi Labs mod in your instance to 0.8.20. Thanks in advance!

**Comment by MojangPlsFix** [comment] 2024-08-30 19:42
> I've fixed it in Labs! However, I have noticed that some of our Groovy Scripts aren't running correctly, seemingly due to obfuscation issues.
> 
> Might be a GroovyScript issue, should report there if you can reproduce in a isolated environment. (seems to be due to `EnumDyeColor.getMetadata()`, `ItemStack.getMetadata()`, and `IFrameable.decorate` (Storage Drawers 5.5.0 Method)
> 
> When I update Labs in Nomi-CEu, I'll close this issue, as the game will no longer be unrunnable.
> 
> If you are available, before I release Labs, can you check that [This Labs Build](https://github.com/Nomi-CEu/Nomi-Labs/actions/runs/10631026525) fixes the crash?

Looks good thx for the quick work. Will investigate the issue with Groovyscripts. Seems to be major, since the PostInit completely crashes...

**Comment by IntegerLimit** [comment] 2024-08-31 04:05
GrS issue seems to be due to obfuscation issues with SpongeForge installed, or SpongeForge removing methods from classes.

**Closed** 2024-08-31 04:19 UTC
Labels: bug, fixed-labs
