### ISSUE TITLE
Assembly line automation bug with ae2

### ISSUE THREAD

**Issue by kirito78320** [Nomi-CEu/Nomi-CEu#742] opened 2024-05-15 13:58 UTC
### Nomi CEu Version

1.7-alpha-4

### Launcher

curse forge

### Configurations or Mods Changed

nothing

### Environment

Multiplayer

### Mode

Expert Mode

### What Happened

The p2p tunnel don't put items in gt pipe , it work one time and not after , i need to disconnect and reconnect the pipe or the p2p to work and it don't work every time i need to manually put item in the input

![2024-05-15_15 58 07](https://github.com/Nomi-CEu/Nomi-CEu/assets/44950353/958cd8a6-67ce-4b94-8d28-9d008c0b185c)

### Expected Behavior

Fix the pipe issue with p2p

**Comment by MatthiasMann** [comment] 2024-05-16 05:23
I used the item laser relays to automate my assembly lines - worked flawlessly (normal mode). Never tried to use the pipe based approach.

**Comment by kirito78320** [comment] 2024-05-16 09:27
> I used the item laser relays to automate my assembly lines - worked flawlessly (normal mode). Never tried to use the pipe based approach.

Yeah , i was using it before , but after an update , the quest book say to use p2p with pipe

**Comment by IntegerLimit** [comment] 2024-05-16 11:31
I am not sure which one is better. Will look into this. Might be fixed with #712.

**Comment by HandsomeAsianMan** [comment] 2024-05-18 20:27
Might be because the item p2p try to input into inventories which the pipe isn't, using a subnet with interface into storage busses on each input bus would be better. Perhaps the quest book should mention this instead of the p2p approach.

**Comment by IntegerLimit** [comment] 2024-05-18 23:37
Would Storage Buses break with Ordered Item Inputs?

**Comment by HandsomeAsianMan** [comment] 2024-05-18 23:38
Could just set priority in storage busses

**Comment by Folanlron** [comment] 2024-05-19 04:45
The p2p Item for use in the AL automation is suppose to tell the AL Sub-net when it has items, it basically activates blocking mode when it detects items in the "First" item Slot(As this is the only item slot you have access to for mutiple sides)

It is not meant to send items.. it's just a "Flag" bus for blocking mode literally, although it is all changing again whenever the stocking bus's/advanced blocking cards get actually added.

**Comment by HandsomeAsianMan** [comment] 2024-05-19 06:11
Y tho? Interface storage bus method already works with blocking mode

**Comment by Folanlron** [comment] 2024-05-30 23:56
I am going to close this as this isn't really a full on "bug"

We are at that weird point of the mods were 1 thing can happen on Alpha/Beta versions, but they do not work that way in current "Release", I would consider it a regression to leave this open, closing.

**Closed by Folanlron** 2024-05-30 23:56 UTC
Labels: bug
