### ISSUE TITLE
my nomifactory world crashes when i launch

### ISSUE THREAD

**Issue by hdks1111** [Nomi-CEu/nomi-ceu#350] opened 2023-05-04 02:41 UTC
crash log:https://mclo.gs/NqXF9e2

**Comment by IntegerLimit** [comment] 2023-05-04 03:04
Please use the provided bug report template.

**Comment by IntegerLimit** [comment] 2023-05-04 03:06
Fixed in 1.6.1 alpha https://www.curseforge.com/minecraft/modpacks/nomi-ceu/files/4494694. Duplicate of https://github.com/Nomi-CEu/nomi-ceu/issues/311.

Next time, use the provided templates.

**Closed by IntegerLimit** 2023-05-04 03:06 UTC
Labels: duplicate, invalid
