### ISSUE TITLE
ME Output Hatches Disappearing

### ISSUE THREAD

**Issue by hapzwo** [Nomi-CEu/Nomi-CEu#671] opened 2024-03-21 02:20 UTC
### Nomi CEu Version

Nightly

### Launcher

Multimc

### Configurations or Mods Changed

Added Custom Multiblocks made by diddy.

### Environment

Singleplayer 1.7 alpha-2 (downloaded from curseforge and imported into multimc)

### Mode

Normal Mode

### What Happened

Using ME output Hatches for Distillation tower Output (due to their infinite storage capacity) but suddenly i log in multiple mins pass with everything running fine, I go to check on my Distillation towers and the ME Output Hatches are missing (controller says incompleted structure) i autocraft some more and try to place them there, The moment i right click to place they dissapear (basically a quick flash of the block being there but instantly disappearing). i though it was something to do with ME Hatches since this is alpha, So i made some output hatches but again the moment i place them they instantly disappear (forgot to mention that it is not an inventory desync as i tried to relog and nothing happened)
![2024-03-21_02 22 09](https://github.com/Nomi-CEu/Nomi-CEu/assets/164284748/767c515d-c400-4b62-a87c-a42b7d9b099d)
. The surprising part is that when i placed regular blocks like xtone tiles/Gregtech Frames they do not act like the hatches.

### Expected Behavior

Expecting The ME Output Hatches to not disappear.

### Reproduction Steps

i do not really know how to trigger the bug, but it is worth to know that this only happened in distillation towers (LCR next to them didn't have his hatches disappear) but it goes as follows:
1.build distillation tower
2.use stocking input hatches and ME Output Hatches
3.wait for bug to happen

### Additional Information

i did not connect all ME Output Hatches to my ME network instead when i noticed that all fluids went down to the lowest ME output hatch I just connected that one

**Comment by hapzwo** [comment] 2024-03-21 02:21
apologies for the wrong info it is not nightly it's directly downloaded from the cf's launcher (idk if that's nightly)

**Comment by IntegerLimit** [comment] 2024-03-21 04:03
Yep Thats 1.7-alpha-2. All good though.

**Comment by IntegerLimit** [comment] 2024-03-21 04:06
Try:

1. Reinstalling the Pack
2. Removing Optifine

If the problem is fixed after that, then close this issue.

If the problem is still there, then it is an actual problem.

Then, please tell me whether this happens on:
- New Worlds
- Both Old and New Worlds on [GT 2.8 Nightly]((https://nightly.link/Nomi-CEu/Nomi-CEu/workflows/testbuildpack/dev%2Fgt-2.8?preview)

Thanks in Advance!

**Comment by IntegerLimit** [comment] 2024-05-19 06:29
Not Reproducable.

**Closed by IntegerLimit** 2024-05-19 06:29 UTC
Labels: bug
