### ISSUE TITLE
Canning Machine manufactured cells disappear or something like that

### ISSUE THREAD

**Issue by jk1895** [Nomi-CEu/Nomi-CEu#547] opened 2023-11-30 19:55 UTC
### Nomi CEu Version

1.6.1a

### Launcher

GDLauncher

### Configurations or Mods Changed

added Flux Networks

### Environment

Singleplayer

### Mode

Expert Mode

### What Happened

As requested, an issue so that you don't forget.

Something is wrong with the crafting of filled cells. They are crafted by the canning machine, but they somehow disappear and the combination crafter then waits forever for them.
If I then cancel the order in the ME system, no filled or half-filled cells appear. Also no unused but prepared packages.

I don't know why this only happens for some and not for all. Otherwise someone would have reported it long ago.

Thank you for taking care of this.

### Expected Behavior

Cells are crafted and passed on to the combination package crafter so that the order can be completed.

**Comment by jk1895** [comment] 2023-12-01 07:40
I know the problem you describe well enough and it is not the case here. The problem you describe can be solved very easily by using a very fast pump (IV+) and filling the fluid interface completely (9x4mB). Then this will not happen.
What I have described is something completely new.

**Comment by MatthiasMann** [comment] 2023-12-01 11:53
Maybe a fluid detector cover and controller cover can disable the canning machine until it has enough fluid?

**Comment by IntegerLimit** [comment] 2023-12-03 22:57
> I know the problem you describe well enough and it is not the case here. The problem you describe can be solved very easily by using a very fast pump (IV+) and filling the fluid interface completely (9x4mB). And of course have plenty of the stuff in stock. Then this will not happen. What I have described is something completely new, but possibly somehow related to the other.

Try just crafting the cells. See if any half-filled cells appear.

**Comment by jk1895** [comment] 2023-12-04 09:18
128 wyvern cores ordered. If I craft the required 512 water cells in advance (they are crafted all at once without any problems, no half-full cells etc.), the 128 wyvern cores are completed. If I don't do this, the task ALWAYS hangs. Always!
![java_P8u3Qdmovy](https://github.com/Nomi-CEu/Nomi-CEu/assets/20401451/30d88865-649e-41c0-973d-fc8affd63008)
![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/20401451/c2d562d2-9edf-47e1-8f96-365e50f4f5c4)
![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/20401451/2e428c80-04ee-4139-9fd2-80d9433bced6)
![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/20401451/a5a9da09-9ebf-4b6d-b39a-7c917dd0c2a3)

**Comment by IntegerLimit** [comment] 2023-12-04 11:53
This is very weird. Now that I think about it, I think I might have observed this issue too...

**Comment by MatthiasMann** [comment] 2023-12-04 18:46
I had a similar issues back in 1.6 where I used an export bus with fuzzy filter to export hot ingots into a freezer. If I requested a full crafting recipe some hot ingots just vanished - but if I do one at a time it always worked.

There is a open bug report for this https://github.com/PrototypeTrousers/Applied-Energistics-2/issues/213 - maybe something similar is happening here? My work around for this issue is to use an EIO advanced item filter to route hot ingots directly to the freezer and no go through AE2 - I haven't noticed something similar to this with other items so far.

**Comment by IntegerLimit** [comment] 2023-12-05 10:06
Also a tip: Use fluid lasers, faster than conduits.

**Comment by Kasra-G** [comment] 2024-01-10 16:40
I've had this issue, specifically with large crafts needing the empowered blocks. It appears that the AE system doesn't want to craft enough cells to complete the craft. I think it might have to do with the empty cells popping off of the combination packaged crafter, maybe the AE system expects them to be inserted back into the system? The problem is that I have a vacuum chest collecting the empty cells and putting them back into the system already, and when I manually insert cells into the system via an interface, it doesn't recognize that either.

I have managed to get around this issue by crafting thousands of empty cells beforehand, and putting a vacuum chest near the packaged crafter setup to put the empty cells back into the network. Although the same issue will occur if I have a craft that uses thousands of empowered blocks

**Comment by v3ect0rgames** [comment] 2024-07-20 00:14
This issue seems to be fixed in the latest update

**Comment by IntegerLimit** [comment] 2024-07-20 00:32
Cannot Reproduce in latest.

**Closed by IntegerLimit** 2024-07-20 00:32 UTC
Labels: bug
