### ISSUE TITLE
Ticking Block Entity Error

### ISSUE THREAD

**Issue by FlyAvalan** [Nomi-CEu/nomi-ceu#379] opened 2023-06-06 21:18 UTC
### Nomi CEu Version

1.6

### Launcher

CurseForge

### Environment

Multiplayer Forge Server

### Mode

N/A

### What Happened

Joined the server and got this error.

```
[16:11:52] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:773) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_362]
Caused by: java.lang.NullPointerException
        at gregtech.api.metatileentity.MetaTileEntity.getCapability(MetaTileEntity.java:999) ~[MetaTileEntity.class:?]
        at gregtech.api.metatileentity.MetaTileEntity.getCoverCapability(MetaTileEntity.java:983) ~[MetaTileEntity.class:?]
        at gregtech.api.metatileentity.MetaTileEntityHolder.getCapability(MetaTileEntityHolder.java:179) ~[MetaTileEntityHolder.class:?]
        at crazypants.enderio.base.capability.ItemTools.getExternalInventory(ItemTools.java:347) ~[ItemTools.class:?]
        at crazypants.enderio.base.capability.ItemTools.getExternalInventory(ItemTools.java:341) ~[ItemTools.class:?]
        at crazypants.enderio.conduits.conduit.item.ItemConduit.getExternalInventory(ItemConduit.java:337) ~[ItemConduit.class:?]
        at crazypants.enderio.conduits.conduit.item.ItemConduit.canConnectToExternal(ItemConduit.java:378) ~[ItemConduit.class:?]
        at crazypants.enderio.conduits.conduit.AbstractConduit.updateConnections(AbstractConduit.java:428) ~[AbstractConduit.class:?]
        at crazypants.enderio.conduits.conduit.AbstractConduit.updateEntity(AbstractConduit.java:399) ~[AbstractConduit.class:?]
        at crazypants.enderio.conduits.conduit.TileConduitBundle.doUpdate(TileConduitBundle.java:339) ~[TileConduitBundle.class:?]
        at com.enderio.core.common.TileEntityBase.update(TileEntityBase.java:49) ~[TileEntityBase.class:?]
        at net.minecraft.world.World.updateEntities(World.java:1838) ~[amu.class:?]
        at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613) ~[oo.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767) ~[MinecraftServer.class:?]
        ... 4 more
[16:11:52] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: /opt/minecraft/./crash-reports/crash-2023-06-06_16.11.52-server.txt
```

Crash Report:
[crash-2023-06-06_16.11.52-server.txt](https://github.com/Nomi-CEu/nomi-ceu/files/11669346/crash-2023-06-06_16.11.52-server.txt)

### Expected Behavior

I expected to be able to just join into my server, but it crashed right when I joined.

### Reproduction Steps

Not Sure.
Other people play this.

### Logs

[crash-2023-06-06_16.11.52-server.txt](https://github.com/Nomi-CEu/nomi-ceu/files/11669353/crash-2023-06-06_16.11.52-server.txt)

**Comment by IntegerLimit** [comment] 2023-06-07 00:46
Known problem. Fixed in alpha and beta versions. Update to 1.6.1-beta-3, 1.6 is very broken.

**Comment by IntegerLimit** [comment] 2023-06-07 00:47
Duplicate of https://github.com/Nomi-CEu/nomi-ceu/issues/328.

**Closed by IntegerLimit** 2023-06-07 00:47 UTC
Labels: bug

**Comment by FlyAvalan** [comment] 2023-06-07 04:27
> Known problem. Fixed in alpha and beta versions. Update to 1.6.1-beta-3, 1.6 is very broken.

Hey thanks, that worked for me.
