### ISSUE TITLE
Unable to make RAM Wafers

### ISSUE THREAD

**Issue by CarePlay34** [Nomi-CEu/Nomi-CEu#708] opened 2024-04-02 02:59 UTC
### Nomi CEu Version

1.7-alpha-4

### Launcher

Prism

### Configurations or Mods Changed

Nothing Significant

### Environment

Server/Multiplayer

### Mode

Expert Mode

### What Happened

Cannot produce RAM Wafers
![Screenshot 2024-04-02 024230](https://github.com/Nomi-CEu/Nomi-CEu/assets/122828262/973f41cc-7e28-4a9f-853e-b9faad49c06c)

### Expected Behavior

Should be able to make RAM Wafers

### Reproduction Steps

Just try to make RAM Wafers in an MV Laser Engraver with an Emerald Lens

**Comment by CarePlay34** [comment] 2024-04-02 16:58
Tried making it in a HV Laser Engraver, didn't work. Tried making it outside the cleanroom, didn't work. Tried with a different lens, didn't work. I'm not seeing a solution here.

**Comment by IntegerLimit** [comment] 2024-04-03 04:19
Its probably something wrong with scripts relating to servers.

Can you send you `latest.log`, `debug.log` and `groovy.log`?

**Comment by IntegerLimit** [comment] 2024-04-03 22:28
Please update your server to 1.7-alpha-4. It is still on 1.7-alpha-3.

Re-update if you believe that you have updated it. Also update your client to 1.7-alpha-4.

**Comment by IntegerLimit** [comment] 2024-04-04 22:50
It is still using 1.7-alpha-3, based on groovy scripts.

Note that the 1.7-alpha-4 server pack is not marked as a server pack, so you have to do some digging to find it.

**Comment by CarePlay34** [comment] 2024-04-04 23:22
I mean I'm literally just straight up unzipping the Alpha 4 server file and playing on it. Only thing that's the same is the world file.

**Comment by IntegerLimit** [comment] 2024-04-05 02:30
Let me check if the alpha 4 server file is broken.

**Comment by CarePlay34** [comment] 2024-04-05 04:05
Sounds good!

**Comment by unplannedlunch** [comment] 2024-04-06 01:25
Just ran into this issue as well- I recently updated from alpha 2 to alpha 4. It looks like the recipe for RAM wafers requires specifically a green glass lens, rather than oredict craftingLensGreen.

**Comment by MatthiasMann** [comment] 2024-04-06 09:30
I just checked with my 1.7-alpha-4 via JEI - the emerald lens can only be used to craft the atomic reconstructor - it has no uses in the laser engraver.

**Comment by IntegerLimit** [comment] 2024-04-07 04:17
I checked this, and sometimes it was oreCraftingLensGreen, and other times it was not... its really weird.

**Comment by MerryMooose** [comment] 2024-04-07 07:19
I'm having a similar problem with the ruby lens not working, JEI says it has no recipes in the engraver, and to make the wafer I want I have to use red glass lens

**Comment by Kamikzu** [comment] 2024-04-07 07:28
maybe it's really weird, but when i update server - i delete folders except backups and world and this help with this problem

**Comment by IntegerLimit** [comment] 2024-04-07 10:45
Yes, I experienced a similar situation, where reinstalling fixed the issue.

**Comment by MatthiasMann** [comment] 2024-04-07 20:15
It's not related to reinstalling - I have restarted my single player instance a few times (same save, no updates of mods / scripts / settings) in between - and sometimes the emerald lens is working (I got 2 stacks of RAMs from it) and other times it's not working. It seems to me that there is a kind of race condition while registering either the lens or the ore dictionaries.

Currently it's not working and the ore dict entries are:
- lensEmerald
- craftingLensGreen

Other gem lenses have the same kind of ore dict - but they work. For example the topaz lens:
- lensTopaz
- craftingLensOrange

While I did craft the topaz lens this game session and used it to make LPIC wafers, the emerald one did not work when I crafted it but did after the next game start.

**Comment by IntegerLimit** [comment] 2024-04-07 21:47
> It's not related to reinstalling - I have restarted my single player instance a few times (same save, no updates of mods / scripts / settings) in between - and sometimes the emerald lens is working (I got 2 stacks of RAMs from it) and other times it's not working. It seems to me that there is a kind of race condition while registering either the lens or the ore dictionaries.
> 
> Currently it's not working and the ore dict entries are:
> 
> * lensEmerald
> * craftingLensGreen
> 
> Other gem lenses have the same kind of ore dict - but they work. For example the topaz lens:
> 
> * lensTopaz
> * craftingLensOrange
> 
> While I did craft the topaz lens this game session and used it to make LPIC wafers, the emerald one did not work when I crafted it but did after the next game start.

The race condition is a good theory. I will look into it with that perspective. Thank you.

**Comment by MatthiasMann** [comment] 2024-04-09 06:24
Just a small update: had this happening with the diamond lens too

**Comment by Kamikzu** [comment] 2024-04-09 06:50
Can you just delete configs folder on server and replace with fresg configs folder from zip?

**Comment by MatthiasMann** [comment] 2024-04-09 07:37
> Can you just delete configs folder on server and replace with fresg configs folder from zip?

If you mean my setup - it is a fresh extract of the alpha-4 server and client files with most of the client side mods installed (I did not install the discord or oauth mods)

**Comment by Kamikzu** [comment] 2024-04-09 08:45
> > Can you just delete configs folder on server and replace with fresg configs folder from zip?
> 
> If you mean my setup - it is a fresh extract of the alpha-4 server and client files with most of the client side mods installed (I did not install the discord or oauth mods)

How you install server? It's hsoting or just started on pc? Maybe you can try unzip server files again with WinRAR. This is I do, to fix this problem (just reinstalled minecraft server, except world and backups folders)

**Comment by MatthiasMann** [comment] 2024-04-09 09:26
> 
> How you install server? It's hsoting or just started on pc? Maybe you can try unzip server files again with WinRAR. This is I do, to fix this problem (just reinstalled minecraft server, except world and backups folders)

It's a local single player instance - this is what I did:
- download the server and client zip files from the github release for alpha-4
- extracted the `nomi-ceu-1.7-alpha-4-server.zip` using Nemo's "extract here" feature (I'm on Linux Mint 21.3)
- extracted the content of the `override` folder of `nomi-ceu-1.7-alpha-4-client.zip` over the previously extracted server files
- extracted the `modlist.html` and used that to download most of the client side mods
- copied my `saves` and `journeymap` folder and the `options.txt` from my alpha-3 install over

This process has worked for every version of this and other mod packs before - so I highly doubt that the issues with the lenses are caused by the installation - **especially** as the lenses work sometimes the instance is started and other times not.

Hmm - what I have not tried yet if the bug state changes when just reloading the world by going back to main menu or if you need to restart Minecraft to change it - will have to experiment.

**Comment by Ult1mateNoob** [comment] 2024-04-13 05:00
> This process has worked for every version of this and other mod packs before - so I highly doubt that the issues with the lenses are caused by the installation - **especially** as the lenses work sometimes the instance is started and other times not.
> 
> Hmm - what I have not tried yet if the bug state changes when just reloading the world by going back to main menu or if you need to restart Minecraft to change it - will have to experiment.
FYI, in my case crafting went normal just after restarting my server without tinkering any file. Also add sapphire lens to the list.

**Comment by Ult1mateNoob** [comment] 2024-04-13 05:02
> This process has worked for every version of this and other mod packs before - so I highly doubt that the issues with the lenses are caused by the installation - **especially** as the lenses work sometimes the instance is started and other times not.
> 
> Hmm - what I have not tried yet if the bug state changes when just reloading the world by going back to main menu or if you need to restart Minecraft to change it - will have to experiment.

FYI, in my case crafting went normal just after restarting my server without tinkering any file. Also add sapphire lens to the list.

**Comment by IntegerLimit** [comment] 2024-04-21 11:51
Fixed here: https://github.com/Nomi-CEu/Nomi-Labs/commit/88b5358308cfdb18031bbfed1b645c9216f2ccb3 

Will update soon.

**Comment by toastonrye** [comment] 2024-05-12 17:55
Just to add to this, I am also on v1.7-alpha-4 same as the person who initially posted this. The recipe is broken according to JEI, but if I use a sapphire lens, the craft does work properly, despite JEI saying it should only work with the blue lens.

**Comment by IntegerLimit** [comment] 2024-05-12 23:10
It is already fixed, will release in beta-5. The JEI vs Actual Recipe is also inconsistent, and sometimes it works as above, and other times it would work the opposite of the above.

**Comment by sreny1** [comment] 2024-06-18 11:34
having this issue on a server currently...
looking forward to alpha 5 being released :)

its been a month and its breaking progression :(

**Closed** 2024-07-11 11:33 UTC
Labels: bug, fixed-next-GTCEu, blocking
