### ISSUE TITLE
Terracotta

### ISSUE THREAD

**Issue by Quikswitch** [Nomi-CEu/nomi-ceu#299] opened 2023-03-25 12:35 UTC
Pack Version:
v1.5.2

Launcher:
Prism Launcher

Mode:
Hard Mode

Environment:
Singleplayer

Description:
Some colors of terracotta cannot be macerated, despite the recipe being in JEI (for every color except uncolored). This includes white and uncolored Terracotta, but not Blue, Yellow, or Orange. This can be a problem if you happen to source clay from a mesa biome, which is extremely easy and fast.

Expected Behavior:
All terracotta colors able to be macerated, or none of them.

Steps To Reproduce:
Attempt to macerate terracotta. Blue, yellow, and orange can be properly macerated. White cannot, despite having a jei recipe, and uncolored also cannot, though it has no appropriate recipe.

Crash Log:
N/A

Screenshots:
N/A

Additional details:
Thanks for making a great pack <3

**Comment by IntegerLimit** [comment] 2023-03-26 00:09
Huh, interesting, will have a look.

**Comment by IntegerLimit** [comment] 2023-04-06 08:25
Confirmed. Maybe a GTCEu problem.

**Comment by IntegerLimit** [comment] 2023-04-14 09:26
Seems to be a GTCEu problem. Please transfer it to https://github.com/GregTechCEu/GregTech/issues.

**Comment by IntegerLimit** [comment] 2023-06-06 05:14
Forgot to close this, this was fixed with 1.6.1-beta-2.

**Closed by IntegerLimit** 2023-06-06 05:14 UTC
Labels: bug, fixed-next-GTCEu
