### ISSUE TITLE
launch.sh not working

### ISSUE THREAD

**Issue by NaTajnacku** [Nomi-CEu/nomi-ceu#331] opened 2023-04-15 21:13 UTC
**Pack Version:**
nomi-ceu-server-1.6.zip

**Launcher:**
launch.sh

**Mode:**
Normal

**Environment:**
Linux Ubuntu desktop

**Description:**
Cant launch server with launch.sh file with terminal or with gui. File launch.sh is set as executable. I have java 8 installed.

![image](https://user-images.githubusercontent.com/88077931/232253242-84cd22ab-568d-4ffe-8d9c-061b91f42686.png)
![Screenshot_1](https://user-images.githubusercontent.com/88077931/232253244-c4135781-92af-49db-b6ac-9eaccbe82c5e.png)

**Comment by IntegerLimit** [comment] 2023-04-16 07:24
Known. Duplicate of https://github.com/Nomi-CEu/nomi-ceu/issues/326.

**Closed by IntegerLimit** 2023-04-16 07:24 UTC
Labels: bug
