### ISSUE TITLE
/dank/null

### ISSUE THREAD

**Issue by JoBanJo** [Nomi-CEu/Nomi-CEu#614] opened 2024-02-10 05:14 UTC
### Nomi CEu Version

1.7-alpha-2a

### Related Problem

Inventory fills with cobblestone and other crab when mining veins. 

### Your Solution

Add a mod like /dank/null 

### How Will Your Solution Work

If the mod is added players have access to an item that holds large amounts of cobblestone and etc.

**Comment by IntegerLimit** [comment] 2024-02-10 05:20
Dupe of https://github.com/Nomi-CEu/Nomi-CEu/issues/345.

**Closed by IntegerLimit** 2024-02-10 05:20 UTC
Labels: enhancement
