### ISSUE TITLE
Regression: Black Steel Recipe Does not Work Again

### ISSUE THREAD

**Issue by lilpaladin1** [Nomi-CEu/nomi-ceu#310] opened 2023-04-08 14:37 UTC
**Pack Version:**
1.6

**Launcher:**
Prism Launcher

**Mode:**
Normal

**Environment:**
Singleplayer

**Description:**
The Black Steel Dust/Fluid Recipe does not work again, it was previously fixed in #84 but with the newest pack release, it has broken again. It is again the NBT version of the Red Coal that is preventing the recipe from running, as using an NBT-less version of the Red Coal from the creative inventory works fine. This probably happened with the introduction of that Dark Red Coal version of the recipe in the Alloy Blast Smelter.

**Expected Behavior:**
The Black Steel Recipe on both the Mixer and Alloy Blast Furnace work.

**Steps To Reproduce:**
Put items in either Mixer or Alloy Blast Furnace.

**Crash Log:**
No Crashing

**Screenshots:**

![javaw_uSJ9ytQPTk](https://user-images.githubusercontent.com/17087669/230726752-8d12eeae-49cd-41c6-a77f-9a976b1cc648.png)

**Comment by IntegerLimit** [comment] 2023-04-08 23:51
This is most likely a GT issue. Not sure though.

**Comment by IntegerLimit** [comment] 2023-04-13 23:33
Yeah, I saw those errors too. Looking at it, and, Black Steel will be implemented in groovy, due to the NBT requirements.

**Comment by lstanden** [comment] 2023-04-15 07:39
FYI, the following change fixed my mixer recipe:
```
Before:
<extrautils2:ingredients:4>

After:
<extrautils2:ingredients:4>.withEmptyTag()
```

**Comment by IntegerLimit** [comment] 2023-04-15 09:49
Oh, really...

**Comment by bhodii** [comment] 2023-04-16 23:25
I can confirm the above, in https://github.com/Nomi-CEu/nomi-ceu/blob/a2efbed8b3c289a57b7323a2bfcddee9ddcbb9f2/overrides/scripts/Earlygame.zs#L195 changing

`mixer.recipeBuilder().inputs([<ore:dustSteel> * 3,<ore:dustBlackBronze> * 2,<actuallyadditions:item_crystal:3> * 2,<extrautils2:ingredients:4> * 2]).outputs(<metaitem:dustBlackSteel>  * 9).EUt(15).duration(200).buildAndRegister();`

to

`mixer.recipeBuilder().inputs([<ore:dustSteel> * 3,<ore:dustBlackBronze> * 2,<actuallyadditions:item_crystal:3> * 2,<extrautils2:ingredients:4>.withEmptyTag() * 2]).outputs(<metaitem:dustBlackSteel>  * 9).EUt(15).duration(200).buildAndRegister();`

allows the mixer to mix black steel.

**Comment by IntegerLimit** [comment] 2023-04-17 01:51
Fixed with https://github.com/Nomi-CEu/nomi-ceu/commit/7a13c1d24b8f5aa1a5d4e3bcc35aeb3a1631fb40.

**Closed by IntegerLimit** 2023-04-17 01:51 UTC
Labels: bug, high-priority

**Comment by omletformage** [comment] 2023-04-17 02:46
when will this be implemented?

**Comment by IntegerLimit** [comment] 2023-04-19 12:35
Has been implemented. Black steel is fixed in 1.6.1 alpha.
