### ISSUE TITLE
Placing Draconic Evolution Energy Core Crashes Save

### ISSUE THREAD

**Issue by TimothyNardi** [Nomi-CEu/Nomi-CEu#538] opened 2023-11-20 04:07 UTC
### Nomi CEu Version

1.7-alpha-1

### Launcher

CurseForge

### Configurations or Mods Changed

Lazy AE2
Flux Networks

### Environment

Singleplayer

### Mode

Normal Mode

### What Happened

I placed the Draconic Evolution Energy Core and the save crashed to title screen. I then attempted to load the save and it crashed on load. I then attempted to reload the Minecraft from launcher and the save still crashed. I then loaded a backup and attempted to place the Energy Core again. It crashed. I don't know why, but have included the most recent crash reports.

This persisted in a different save file.

### Expected Behavior

Not to crash.

### Reproduction Steps

Place Draconic Evolution Energy Core.

### Logs

[crash-2023-11-19_21.50.41-client.txt](https://github.com/Nomi-CEu/Nomi-CEu/files/13406148/crash-2023-11-19_21.50.41-client.txt)
[crash-2023-11-19_21.50.31-server.txt](https://github.com/Nomi-CEu/Nomi-CEu/files/13406149/crash-2023-11-19_21.50.31-server.txt)
[crash-2023-11-19_21.48.39-client.txt](https://github.com/Nomi-CEu/Nomi-CEu/files/13406150/crash-2023-11-19_21.48.39-client.txt)
[crash-2023-11-19_21.48.27-server.txt](https://github.com/Nomi-CEu/Nomi-CEu/files/13406151/crash-2023-11-19_21.48.27-server.txt)

**Comment by Folanlron** [comment] 2023-11-20 07:04
Has been fixed, they are waiting for things to get cleared up on other things.

Hopefully a new alpha soon, but I'm not sure when.

https://github.com/Nomi-CEu/Nomi-CEu/pull/484

**Comment by IntegerLimit** [comment] 2023-11-21 00:57
Already been fixed. Alpha will release soon. You can download the latest build from the nightly build page: https://nightly.link/Nomi-CEu/Nomi-CEu/workflows/testbuildpack/main.

Closed as completed, with #484.

**Comment by IntegerLimit** [comment] 2023-11-21 00:58
It was actually our problem, caused by our bansoukou patches.

**Closed by IntegerLimit** 2023-11-21 00:57 UTC
Labels: bug, status: confirmed, other-mods-problems
