### ISSUE TITLE
Sulfur Trioxide cannot be crafted in the Large Chemical Reactor

### ISSUE THREAD

**Issue by felix-schneider** [Nomi-CEu/nomi-ceu#284] opened 2023-03-12 15:11 UTC
**Pack Version:**
1.5.2

**Launcher:**
MCLauncher

**Mode:**
**Hard mode only** it works in normal mode.

**Environment:**
Singleplayer

**Description:**
As the title says. It works in the regular chemical reactor, as do other recipes which use a catalyst.
**Expected Behavior:**
The large chemical reactor should be able to make any recipe that a regular reactor can make.

**Steps To Reproduce:**
Build a large chem reactor. Insert inputs. Nothing happens

**Crash Log:**
N/A

**Screenshots:**
N/A

**Comment by felix-schneider** [comment] 2023-03-12 15:41
Update: I also tried Fluoroantimonic Acid, which also uses a catalyst, and it also does not work.

**Comment by felix-schneider** [comment] 2023-03-12 16:05
This is very strange. Other, similar recipes work, like Fluoroantimonic Acid. It is also added by CraftTweaker, it also uses a catalyst, but that one works and Sulfur Trioxide doesn't

**Comment by IntegerLimit** [comment] 2023-03-12 23:55
Huh, I'll investigate this.

**Comment by IntegerLimit** [comment] 2023-03-13 01:24
Huh, I can reproduce this, investigating further.

**Comment by IntegerLimit** [comment] 2023-03-13 01:24
Does this happen before 1.5.2?

**Comment by IntegerLimit** [comment] 2023-03-13 01:24
Also, are there other recipes that are like this one?

**Comment by IntegerLimit** [comment] 2023-03-13 01:27
Elemental Reduction seems to work...

**Comment by Correlander** [comment] 2023-03-13 01:33
> Does this happen before 1.5.2?

no

**Comment by Correlander** [comment] 2023-03-13 01:33
> Also, are there other recipes that are like this one?

not that me or him could find

**Comment by IntegerLimit** [comment] 2023-03-13 01:37
If my theory was correct, fluoroantimonic acid also won't work. But it does, so my theory is wrong.

**Comment by IntegerLimit** [comment] 2023-03-13 06:46
Officially a GTCEu problem. We can't do anything about it, we'll have to wait for next GTCEu release.

**Comment by IntegerLimit** [comment] 2023-03-31 11:33
High-Priority doesn't really make sense, since it is a GTCEu problem.

**Comment by IntegerLimit** [comment] 2023-04-08 07:58
fixed with https://github.com/Nomi-CEu/nomi-ceu/commit/e50d68415b3352ff5bf10bcbcd6a9d230019a8ed.

**Closed** 2023-04-08 07:58 UTC
Labels: bug, fixed-next-GTCEu
