### ISSUE TITLE
Black Steel is impossible to craft in multiplayer in latest nightly

### ISSUE THREAD

**Issue by Kamikzu** [Nomi-CEu/Nomi-CEu#636] opened 2024-03-04 20:23 UTC
### Nomi CEu Version

1.7-alpha-2a

### Launcher

Prism Launcher

### Configurations or Mods Changed

Alpheim version 1.1.1
Red Core version 0.5.1

### Environment

Forge Server

### Mode

Normal Mode

### What Happened

It is impossible to craft black steel on the server.
![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/113759044/b5c7f367-fc2d-429f-bfdc-1dbfd2b500bf)
![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/113759044/ad17ac79-8fc7-4af6-b544-96567c89462b)

### Expected Behavior

Expected this
![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/113759044/ec24be67-0b43-4486-87cc-2e6bcb13f23f)

### Reproduction Steps

1. start launch.bat from server.zip 
2. enter this world

**Comment by IntegerLimit** [comment] 2024-03-05 11:27
😔

**Comment by IntegerLimit** [comment] 2024-03-05 11:34
@Kamikzu can you do F3+H then press shift+ctrl while hovering over the red coal you had, to show the nbt? And did this happen only in multiplayer, or in both multiplayer and singleplayer?

**Comment by IntegerLimit** [comment] 2024-03-05 11:35
And are you sure both the server and your client is on latest nightly? (at the time of comment, it is 3d73b81)

**Comment by IntegerLimit** [comment] 2024-03-05 11:37
I have reproduced the issue. The red coal has no nbt.

**Comment by Kamikzu** [comment] 2024-03-05 11:39
> And are you sure both the server and your client is on latest nightly? (at the time of comment, it is [3d73b81](https://github.com/Nomi-CEu/Nomi-CEu/commit/3d73b81a6c26b5d615496baf4f87925a34e0f4aa))

![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/113759044/f24e8280-5456-4326-b7a5-bb9f545a0834)

**Comment by IntegerLimit** [comment] 2024-03-05 11:40
The issue is because GS crashes on server due to an error in 'hand_framing.groovy'.

If you want to get rid of it right now, delete that script server side.

**Comment by Kamikzu** [comment] 2024-03-05 11:41
Okay, I'll give it a shot. Thanks for the reply

**Comment by Kamikzu** [comment] 2024-03-05 11:43
> The issue is because GS crashes on server due to an error in 'hand_framing.groovy'.
> 
> If you want to get rid of it right now, delete that script server side.

Is this script responsible for anything important?

**Comment by IntegerLimit** [comment] 2024-03-05 11:48
> > The issue is because GS crashes on server due to an error in 'hand_framing.groovy'.
> > If you want to get rid of it right now, delete that script server side.
> 
> Is this script responsible for anything important?

Hand Framing Dummy Recipes. Aka Hand Framing Recipes showing up in JEI. And craft recipe of Hand Framing Tool.

You might have to remove it in client too.

I am investigating it now, shouldn't be too long tho.

**Comment by Kamikzu** [comment] 2024-03-05 11:50
got it

**Comment by IntegerLimit** [comment] 2024-03-05 11:58
After investigating, seems like an issue on GroovyScript's side. Might be a while for the fix to arrive.

For now, delete the script on server and client.

Its located at `groovy/postInit/handFraming.groovy`

**Comment by Kamikzu** [comment] 2024-03-05 12:07
Can you tell me what to do after removal? I restarted the server, but the problem remains

**Comment by Kamikzu** [comment] 2024-03-05 12:10
> Can you tell me what to do after removal? I restarted the server, but the problem remains
![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/113759044/dbcf6fe7-8826-4fa5-b543-8c6ed974b2fe)
![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/113759044/6aebb585-9f37-4632-9a1f-37c7cec6ce9f)
![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/113759044/19e426cd-4302-4ca5-b006-0b178fcb5163)

**Comment by IntegerLimit** [comment] 2024-03-05 23:49
Does it work after you delete the script?

**Comment by Kamikzu** [comment] 2024-03-05 23:58
Yeah, it worked

**Comment by IntegerLimit** [comment] 2024-03-06 03:51
I have fixed it. It requires a Nomi-Labs update (which is being made right now). When that is done, I will update Nomi-Labs, and commit the groovy file change. It should be fixed post that.

**Comment by IntegerLimit** [comment] 2024-03-06 04:39
Fixed by https://github.com/Nomi-CEu/Nomi-CEu/commit/f11c63d529d0a6d56c67cecd5e201253c9d79de3.

**Closed** 2024-03-06 04:44 UTC
Labels: bug, high-priority, blocking
