### ISSUE TITLE
Microverse Projector Casings mined with Pickaxe instead of Wrench

### ISSUE THREAD

**Issue by toaster128** [Nomi-CEu/Nomi-CEu#988] opened 2024-09-06 02:39 UTC
### Nomi CEu Version

1.6.1b

### Launcher

ATLauncher

### Environment

Forge Server

### Mode

Normal Mode

### What Happened

Microverse Projector Casing is mined with Pickaxe.

### Expected Behavior

Microverse Projector Casing is mined with a Wrench, like all other casings.

### Reproduction Steps

1. Place Microverse Projector Casing
2. Hover over it using The One Probe
3. See it is mined with pickaxe
4. Mine it with a Pickaxe at full speed.
5. Fail to mine it with a wrench.

**Comment by IntegerLimit** [comment] 2024-09-06 04:39
Fixed in 1.7a.

**Comment by IntegerLimit** [comment] 2024-09-06 04:39
Duplicate of https://github.com/Nomi-CEu/Nomi-CEu/issues/726.

**Closed by IntegerLimit** 2024-09-06 04:39 UTC
Labels: duplicate
