### ISSUE TITLE
In special cases, the distillation tower of "GCYM" will not output liquid in "Distillery" mode

### ISSUE THREAD

**Issue by WhitePr** [Nomi-CEu/Nomi-CEu#878] opened 2024-08-08 07:36 UTC
### Nomi CEu Version

1.7-beta-5c

### Launcher

Prism

### Configurations or Mods Changed

AE2FC:2.5.4-r
Lazy AE2:1.1.26

### Environment

Singleplayer

### Mode

Expert Mode

### What Happened

Under special circumstances,  "GCYM" distillation tower will not produce fluid in "Distillery" mode

### Expected Behavior

They should be produced simultaneously

### Reproduction Steps

https://github.com/Nomi-CEu/Nomi-CEu/issues/878#issuecomment-2277085129

**Comment by WhitePr** [comment] 2024-08-08 07:47
https://github.com/user-attachments/assets/88f997ea-1495-44e9-9044-0c101a2f9225

**Comment by WhitePr** [comment] 2024-08-08 08:08
No hydrochloric acid is produced during the distillation of "Acidic Osmium Solution"

[Screencast.webm](https://github.com/user-attachments/assets/be169d73-fda0-449e-97db-120b1245e45b)

**Comment by Folanlron** [comment] 2024-08-08 08:25
The Distilation Towers don't work with Quad/9x Output hatches at all, (this is intended behavior)

So of course it's gonna void fluids with a hatch it can't use.

**Comment by WhitePr** [comment] 2024-08-08 08:36
> The Distilation Towers don't work with Quad/9x Output hatches at all, (this is intended behavior)
> 
> So of course it's gonna void fluids with a hatch it can't use.

Good idea
But same result on 1x output hatch
[Screencast.webm](https://github.com/user-attachments/assets/9b64ee3e-cf69-4788-8c01-f87563d66739)

**Comment by Folanlron** [comment] 2024-08-08 17:29
The Distillation Towers both of them still follow the same rules as any other Distil Tower.

Items, are output the bottom, while fluid is output in each layer There is no way around this, you keeping the input bus on the third layer, is deleting the output fluid.

**Comment by WhitePr** [comment] 2024-08-09 02:48
> Items, are output the bottom, while fluid is output in each layer there is no way around this, you keeping the output bus on the third layer, is deleting the output fluid.

This is true for the "gregtech" distillation tower, but for the "GCYM" distillation tower, its fluid output chamber starts from the third layer.
![Screenshot from 2024-08-09 11-40-36](https://github.com/user-attachments/assets/b260a4da-c21b-42c8-9149-e9820c701c16)

If you had built a "GCYM" distillation tower, you wouldn't have asked this question. PLEASE USE JEI

this is a screenshot of the recipes for "Naquadah Oxide Aero Solution" and "Acidic Osmium Solution"

![Screenshot from 2024-08-09 11-47-43](https://github.com/user-attachments/assets/58328090-a72d-49cf-935d-760fcf39f682)
![Screenshot from 2024-08-09 11-48-09](https://github.com/user-attachments/assets/e3171d9f-a0cc-4594-a461-487317a6e19b)

**Comment by IntegerLimit** [comment] 2024-08-09 03:29
Either way, the GCYM distillation tower should NOT accept quad/non output hatches in its structure, so I'll fix that.

I'll also try and reproduce the issue reported here.

**Comment by WhitePr** [comment] 2024-08-09 03:46
After many attempts, I came to the following conclusions

Take "Naquadah Oxide Aero Solution" as an example
First case:
1.When the "Distillation Tower" of "GCYM" is built, change the default "Distillation Tower" mode to "Distillation Chamber" mode
2.Enter "Naquadah Oxide Aero Solution" and change "Ghost Circuit" to 1
3.The distillation Tower will output fluid
4.Save and exit the world (Or destroy any block of the distillation tower and put it back)
5.The distillation Tower will not output fluid

Second case:
1.When the "Distillation Tower" of "GCYM" is built, but do not change the default "Distillation Tower" mode to "Distillation Chamber" mode
2.Enter "Naquadah Oxide Aero Solution" and change "Ghost Circuit" to 1
3.Change the default "Distillation Tower" mode to "Distillation Chamber" mode in Distillation Tower
4. Distillation Tower is not work
5.Save and exit the world (Or destroy any block of the distillation tower and put it back)
6.Distillation Tower is work, but not output fluid

**Comment by WhitePr** [comment] 2024-08-09 04:04
> After many attempts, I came to the following conclusions
> 
> Take "Naquadah Oxide Aero Solution" as an example First case: 1.When the "Distillation Tower" of "GCYM" is built, change the default "Distillation Tower" mode to "Distillation Chamber" mode 2.Enter "Naquadah Oxide Aero Solution" and change "Ghost Circuit" to 1 3.The distillation Tower will output "Zephyrean Aerotheum" 4.Save and exit the world (Or destroy any block of the distillation tower and put it back) 5.The distillation Tower will not output "Zephyrean Aerotheum"
> 
> Second case: 1.When the "Distillation Tower" of "GCYM" is built, but do not change the default "Distillation Tower" mode to "Distillation Chamber" mode 2.Enter "Naquadah Oxide Aero Solution" and change "Ghost Circuit" to 1 3.Change the default "Distillation Tower" mode to "Distillation Chamber" mode in Distillation Tower 4. Distillation Tower is not work 5.Save and exit the world (Or destroy any block of the distillation tower and put it back) 6.Distillation Tower is work, but not output "Zephyrean Aerotheum"

This phenomenon occurs not only in the formula added by "Nomi-Labs", but also in the formula of "GregTech" itself, such as:
Heavy fuel -> toluene
Heavy fuel -> phenol
Heavy fuel -> benzene

**Comment by IntegerLimit** [comment] 2024-08-09 06:32
Wait, I need to know:

Do the fluids that you are mentioning have a corresponding recipe in the Distillation Tower, or are they Distillery only recipes?

**Comment by WhitePr** [comment] 2024-08-09 06:41
> Wait, I need to know:
> 
> Do the fluids that you are mentioning have a corresponding recipe in the Distillation Tower, or are they Distillery only recipes?

ummm...
Among the formulas I tested, most of them only have the distillation recipe and no distillation tower recipe, but "Acidic Osmium Solution" is an exception, it has both distillation tower recipe and distillation recipe, but it also has this problem

**Comment by WhitePr** [comment] 2024-08-09 07:07
> Wait, I need to know:
> 
> Do the fluids that you are mentioning have a corresponding recipe in the Distillation Tower, or are they Distillery only recipes?

I tried "Lightly Hydro-Cracked Heavy Fuel" and had the same problem. However, I changed a little; I made the "Distillation Tower" 6 stories high to accommodate all the liquid that can be produced when using the "Distillation Tower" mode, and then I followed the steps in https://github.com/Nomi-CEu/Nomi-CEu/issues/878#issuecomment-2277085129, but the result was still the same.

**Comment by IntegerLimit** [comment] 2024-08-10 05:17
Will be fixed in the upcoming GCYM update.

**Closed** 2024-08-11 22:23 UTC
Labels: bug
