### ISSUE TITLE
Picking up hydrogen with a bucket turns it into an Advanced Rocketry hydrogen tank.

### ISSUE THREAD

**Issue by XnoobSpeakable** [Nomi-CEu/nomi-ceu#329] opened 2023-04-14 12:32 UTC
**Pack Version:**
1.6, downloaded from CurseForge app.

**Launcher:**
CurseForge launcher, don't have other launchers so can't test for other launchers

**Mode:**
Normal Mode

**Environment:**
Singleplayer, no changed mods. Bug is reproducible only in survival mode.

**Description:**
If there's hydrogen gas placed in the world, and you pick it up with an empty bucket by right clicking, your empty bucket turns into an Advanced Rocketry Tank of Hydrogen.

**Expected Behavior:**
Your empty bucket should turn into a hydrogen bucket, not a tank.

**Steps To Reproduce:**
Place down hydrogen in the world
Make sure you're in survival mode
Pick the hydrogen up with an empty bucket

**Comment by XnoobSpeakable** [comment] 2023-04-14 12:36
Also happens with oxygen

**Comment by IntegerLimit** [comment] 2023-04-14 23:24
This cannot be fixed, it is a AR issue. Duplicate of https://github.com/Nomi-CEu/nomi-ceu/issues/276.

**Closed by IntegerLimit** 2023-04-14 23:24 UTC
Labels: bug
