### ISSUE TITLE
Old LPIC wafer recipe exists in JEI but has been removed.

### ISSUE THREAD

**Issue by A-E-C-H-ARV** [Nomi-CEu/Nomi-CEu#688] opened 2024-03-26 18:22 UTC
### Nomi CEu Version

1.7-alpha-3

### Launcher

Curse

### Configurations or Mods Changed

AE2FCR

### Environment

Server multiplayer

### Mode

Normal Mode

### What Happened

LPIC wafer recipe in JEI for silcon wafer and orange (topaz) lens still exists for laser engraver at **MV**, despite the recipe being removed and thus doesn't actually work in the engraver. The cutting machine recipes for the LPIC wafer all take **HV** and a cleanrrom.
![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/86379240/7d7527b0-a88f-4577-83cc-2b7c94704a79)

![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/86379240/69a781e5-108e-4130-be1e-2b74fa06ba81)

### Expected Behavior

N/A

### Reproduction Steps

Check JEI for recipe

**Comment by IntegerLimit** [comment] 2024-03-27 11:21
The problem is not that it doesn't work in general, the problem is that it only works for orange lenses, and not for topaz lens.

**Comment by IntegerLimit** [comment] 2024-03-27 11:23
It seems that none of the recipes involving orange lenses work with topaz lenses.

**Comment by IntegerLimit** [comment] 2024-03-27 21:16
## Broken Lens Recipes:
- [ ] Recipe for Inscriber Silicon Press (Should accept diamond and enderpearl and blue topaz and light blue glass)
- [ ] Orange Glass Lens recipes need to work with Topaz

**Comment by IntegerLimit** [comment] 2024-03-28 11:21
Closed as cannot reproduce. (Re-open if issue still occurs on latest nightly)

**Closed by IntegerLimit** 2024-03-28 11:21 UTC
Labels: bug

**Comment by A-E-C-H-ARV** [comment] 2024-03-28 23:31
Seems to have been my fault sorry. Checked singleplayer and the recipes worked so I reinstalled server completely and has resolved the problem
