### ISSUE TITLE
Server hangs when joining during backup

### ISSUE THREAD

**Issue by heggico** [Nomi-CEu/nomi-ceu#396] opened 2023-07-15 15:38 UTC
### Nomi CEu Version

1.6.1-beta-3a

### Launcher

Headless server

### Configurations or Mods Changed

All addon mods installed. 
Dynmap
Mc2discord

### Environment

Forge server

### Mode

Normal Mode

### What Happened

Every time a backup is running from ftb backup everything works as expected.

However, as soon as someone joins the server during a backup, the server gets stuck and doesn't respond untill the backup is completed. If we're lucky the backup was near completion, otherwise the watchdog might kick in and restart the server.

### Expected Behavior

Player can join during a backup operation

### Reproduction Steps

1. Be online on the server
2. Wait for an automatic backup, or run /ftb ackup start
3. Have another player join

### Logs

No crash, just stuck untill complete, or watchdog interrupts

### Additional Information

I've ran the server in docker. Currently moved it to a vm (as a new install. Only the world files Re a direct copy)

Same behaviour for both.

**Comment by IntegerLimit** [comment] 2023-07-15 23:07
This sounds like a problem with either hardware maxing out (CPU or RAM), or a bug with FTB Backups. Either way, we can't really fix this problem.

I recommend checking if your hardware is maxing out. If not, you could try making an issue at https://github.com/FTBTeam/FTB-Mods-Issues/issues. If you do so, make sure you state that the issue is for 1.12.2 in the issue title, and link this issue in the description of that issue.

Hope this helps! I'll mark this as invalid/wontfix and close this issue, but if that issue gets resolved, or it is the fault of hardware maxing out, post a comment here, and I'll either change the close state, or re-open it and close it with updating ftb-backups (or similar, like switching to a fork, or updating ftb-utils and using that for backups instead).

If you find another backup mod that is similar in function, and seems to not have the problem, post it here, and we might replace ftb-backups. However, this will depend on many factors, and would probably need a good discussion.

**Comment by IntegerLimit** [comment] 2023-07-15 23:08
I have implied this in my previous comment, but I'll make it a bit more clear here:
You can try allocating more RAM.

**Closed by IntegerLimit** 2023-07-15 23:07 UTC
Labels: bug

**Comment by heggico** [comment] 2023-07-15 23:23
Ram is set to 8GB, which it hasn't maxed out yet. Same as the CPU.
I was kinda hoping it might have been a lesser know issue. I'll check the FTB backups  for comparable issues first.
Thanks for your reply!

**Comment by Folanlron** [comment] 2023-07-16 03:59
Test it without Dynmap/mc2Discord(Why?)..
