### ISSUE TITLE
Chunks near the obsidian platform in the void world are cleared on save and reload

### ISSUE THREAD

**Issue by pereze2** [Nomi-CEu/Nomi-CEu#246] opened 2023-02-09 04:00 UTC
**Pack Version:**
1.5

**Description:**
Obsidian platform you spawn into the void world (and the chunk it's in and some around it) are being cleared when you save and quit and subsequently reload. No matter what I try, it seems to happen after every time I save and quit and reload. Occurs if I save and quit in void world and lost cities dimension.

**Expected Behavior:**
Expect chunks in void world to not disappear between save/reloads.

**Steps To Reproduce:**
Use Void Cake to access void world. Fill four chunks around the obsidian platform with cobblestone to create one contiguous platform at the same Y level, placing the obsidian platform as close to the center chunk intersection as possible. Save and quit game. Reload world. Two of the four chunks (including the one that included the void platform) will be cleared. This may cause an infinite falling loop, but you should be able to guide to the two remaining chunks. At this point, use overworld cake to return to lost cities. Use void cake to return to void world and recreate obsidian platform. Place some blocks in the two cleared chunks. Save and quit, making sure to stand in the chunks that weren't previously cleared. Reload game. Anything placed in the two chunks will again be cleared.

**Crash Log:**
No crash. No error message. Some log entries that may be relevant:
[19:19:02] [Chunk I/O Executor Thread-1/ERROR]: Chunk file at -8,3 is in the wrong location; relocating. (Expected -8, 3, got -21, 12)
[19:19:02] [Server thread/WARN]: GregTech loaded a new chunk [-10, 5] in dimension 119 (JED Surface Loaded 0) while populating chunk [-12, 3], causing cascading worldgen lag.
[19:19:02] [Server thread/WARN]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
[19:19:02] [Chunk I/O Executor Thread-1/WARN]: Invalid chunk: (16, 5) Offset: 0 Invalid Size: 0 C:\Users\**********\curseforge\minecraft\Instances\Nomifactory (GTCEu Port)\saves\nominate\DIM119\region\r.0.0.mca
[19:19:02] [Server thread/WARN]: Invalid chunk: (16, 5) Offset: 0 Invalid Size: 0 C:\Users\**********\curseforge\minecraft\Instances\Nomifactory (GTCEu Port)\saves\nominate\DIM119\region\r.0.0.mca
[19:19:02] [Server thread/WARN]: Invalid chunk: (16, 5) Offset: 0 Invalid Size: 0 C:\Users\**********\curseforge\minecraft\Instances\Nomifactory (GTCEu Port)\saves\nominate\DIM119\region\r.0.0.mca
[19:19:02] [Server thread/WARN]: GregTech loaded a new chunk [16, 5] in dimension 119 (JED Surface Loaded 0) while populating chunk [12, 0], causing cascading worldgen lag.
[19:19:02] [Server thread/WARN]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.

**Screenshots:**

**Comment by pereze2** [comment] 2023-02-09 18:04
That's odd, out of curiosity I installed the Nomifactory modpack (v1.2.2.1) just to see if I could recreate it in that pack, but I couldn't. Now that I look, it looks like the versions of dimensional edibles are slightly different, though, so I'll give it a shot.

**Comment by IntegerLimit** [comment] 2023-02-09 21:22
Really? Can you tell me the difference and see if updating/downgrading the mod fixes the issue?

**Comment by pereze2** [comment] 2023-02-09 22:18
Nomifactory: DimensionalEdibles-1.12.2-1.6.0.jar
Nomifactory (GTCEu): DimensionalEdibles-1.12.2-1.6.4.jar

Not sure I'll be able to get to try downgrading and testing today, but will post back when I do. I also still need to get to posting the issue on their git.

**Comment by IntegerLimit** [comment] 2023-02-09 23:44
Ok, thanks! It's just very weird how I've never experienced or heard of this issue before. Are you using the CurseForge launcher? You could try changing launchers to something like Prism, the CurseForge launcher seems to have issues.

**Comment by pereze2** [comment] 2023-02-10 00:33
I am using the curseforge launcher. I will definitely give Prism a try.

**Comment by pereze2** [comment] 2023-02-10 01:06
Quick update, I downgraded to 1.6.0 and the issue persisted until I started a new world. Can't recreate the issue in the new world with the lower version.

**Comment by pereze2** [comment] 2023-02-11 04:43
Tried installing 1.5 pack using Prism...and I can't recreate the issue! I even double checked to make sure it was still the 1.6.4 of edibles and it was. Very weird.

Thanks for the tip on Prism.

**Comment by IntegerLimit** [comment] 2023-02-11 08:39
Yeah, CF launcher is so weird, and it causes so many problems. Glad you do not have the problems! Have fun!

**Comment by pereze2** [comment] 2023-02-11 17:56
Spoke too soon. I was thrown off because the chunk with the obsidian platform wasn't disappearing, but one of the surrounding chunks was. I'm going to try reverting back to the 1.6.0 version of edibles and play around for a bit and see what happens.

**Comment by IntegerLimit** [comment] 2023-02-12 01:16
Okay, thanks. Tell me your results afterwards.

**Comment by IntegerLimit** [comment] 2023-02-19 04:46
Are you playing in Singleplayer or Multiplayer?
Does this happen for you in 1.5.1?

**Comment by IntegerLimit** [comment] 2023-03-18 06:29
Does this still happen in 1,5,2? If it does, did downgrading to 1.6 fix it?

**Comment by IntegerLimit** [comment] 2024-07-04 12:37
This was most likely an issue with Just Enough Dimensions, and will be replaced in the next labs update (where its void world will be replaced by a custom one)

**Comment by IntegerLimit** [comment] 2024-07-06 00:00
Update: the obsidian platform is generated by DimensionalEdibles, but the void dimension uses weird saving mechanisms. Hopefully, any voiding issues should be fixed with the custom dimension and https://github.com/Nomifactory/DimensionalEdibles/pull/36 (which will be mixin applied into the next Labs update if required)

**Comment by Exaxxion** [comment] 2024-07-06 00:29
All the cakes do is take you to the dimension and generate a platform under you. It probably marks the chunk as dirty so the game ends up saving it, but it shouldn't cause any kind of voiding.

I'm interested to hear more about the JED problem, as this is the first I recall hearing anything about JED not saving the void dimension properly since we originally switched to it for Omni in 2020.

**Comment by IntegerLimit** [comment] 2024-07-06 00:47
> All the cakes do is take you to the dimension and generate a platform under you. It probably marks the chunk as dirty so the game ends up saving it, but it shouldn't cause any kind of voiding.
> 
> I'm interested to hear more about the JED problem, as this is the first I recall hearing anything about JED not saving the void dimension properly since we originally switched to it for Omni in 2020.

The voiding issue is actually really easy to reproduce:
1. Go to the void world with the void world cake, and replace one of the obsidian blocks with a chest. You can place something inside the chest if you would like.
2. Go to the overworld via any method
3. Go to the void world with the void world cake. Chest gets replaced by obsidian (due to the check being for `fullBlock` instead of `air`

The voiding issue with JED seems just to be an one off issue, probably related to bad installs or corrupted saves. Haven't seen it since.

**Comment by IntegerLimit** [comment] 2024-07-06 00:53
> [19:19:02] [Chunk I/O Executor Thread-1/ERROR]: Chunk file at -8,3 is in the wrong location; relocating. (Expected -8, 3, got -21, 12)

This is most likely the cause of the voiding chunks issue, relating to either corrupt saves or JED changing up save mechanisms of its dimensions.

**Closed** 2024-07-11 11:32 UTC
Labels: bug, fixed-labs
