### ISSUE TITLE
Difficulty forced to Normal

### ISSUE THREAD

**Issue by a-a-GiTHuB-a-a** [Nomi-CEu/Nomi-CEu#586] opened 2023-12-30 17:49 UTC
### Nomi CEu Version

1.6.1a

### Launcher

CurseForge (likely doesn't affect it)

### Environment

Singleplayer

### Mode

Normal Mode

### What Happened

Because I'm a noob, I set the difficulty of my world to Peaceful so I wouldn't have to deal with the mobs. However, after some time, the difficulty was reverted to Normal. This continues to occur. Every time I set the difficulty to Peaceful, it goes back to Normal after some time, and I don't want to lock the difficulty.

### Expected Behavior

The difficulty wouldn't change on its own.

### Reproduction Steps

1. change the difficulty to peaceful
2. maybe it has to do with claiming chunks or `/home`, but wait some time
3. the difficulty changes back

### Additional Information

It might be because I used /home or claimed chunks.

**Comment by IntegerLimit** [comment] 2023-12-31 00:23
This is caused by... some mod, I forgot. This can be fixed by doing `/difficulty peaceful` instead of changing it via the options menu, and doing this for each dimension (especially Void World, its somewhat seperate). We can't fix this.

**Closed by IntegerLimit** 2023-12-31 00:23 UTC
Labels: bug

**Comment by a-a-GiTHuB-a-a** [comment] 2023-12-31 01:23
I did some testing, and the bug is caused by Dimensional Edibles—specifically, teleporting with a cake.

**Comment by a-a-GiTHuB-a-a** [comment] 2023-12-31 02:18
In addition, trying to use `/difficulty` simply says "You do not have permission to use this command".

**Comment by IntegerLimit** [comment] 2023-12-31 03:31
Yes, you do need cheats to be on. If you are on the server, make sure its done via `server.properties`, otherwise use the open to lan way to get cheats. You can also do it via the pause menu if you are on 1.7-a-1+.

I think its actually to do with Just Enough Dimensions, not Dimensional Edibles, but again, I am pretty sure we cannot fix this.
