### ISSUE TITLE
Using Mordor Pearls to throw at ME glass cables will cause the game to crash!

### ISSUE THREAD

**Issue by superDoubleXZ** [Nomi-CEu/Nomi-CEu#713] opened 2024-04-04 18:09 UTC
### Nomi CEu Version

1.7-alpha-2a

### Launcher

Prism Launcher

### Configurations or Mods Changed

AE2 Fluid Crafting Rework

### Environment

Forge Server

### Mode

Normal Mode

### What Happened

The game crashes when you drop the Mordor Pearl to the place shown in the picture.
![3272370c0e26109951799107d6e23003_720](https://github.com/Nomi-CEu/Nomi-CEu/assets/84081028/ae892a44-0f80-4885-8e79-3dac2a5668c4)

### Expected Behavior

The game shouldn't crash, maybe nothing will happen?

### Reproduction Steps

Throw the Pearl of Mordor at this location and the game crashes.
![3272370c0e26109951799107d6e23003_720](https://github.com/Nomi-CEu/Nomi-CEu/assets/84081028/bf5e05cd-dd4b-495c-b691-890d32627056)

### Logs

https://mclo.gs/XRyoRXY
https://mclo.gs/5oqzRUy

**Comment by IntegerLimit** [comment] 2024-04-07 21:48
I'm not sure we can actually fix this. However, will look into it.

**Comment by IntegerLimit** [comment] 2024-07-12 06:51
Can't reproduce in current dev. Might have been fixed by updating AE2.

**Closed by IntegerLimit** 2024-07-12 06:51 UTC
Labels: bug
