### ISSUE TITLE
Endervoir not generating more water

### ISSUE THREAD

**Issue by Munsterlandr** [Nomi-CEu/Nomi-CEu#918] opened 2024-08-16 22:40 UTC
### Nomi CEu Version

1.7-beta-6

### Launcher

Prism Launcher

### Configurations or Mods Changed

Added Ears, it shouldn't be affecting much tho

### Environment

Singleplayer, tested both on worlds in an instance that updated from 1.7-beta5c and a fresh install.

### Mode

Normal Mode

### What Happened

Endervoir would not produce any water, even if two or more buckets are inside of it.

### Expected Behavior

If the Endervoir has two or more buckets of water in it, it should produce more water at a rate of 1 block per second.

### Additional Information

Saw a similar issue that was closed, but it didn't mention how the Endervoir didn't fill up with more water, hence this being separate.

**Comment by CrossElectronics** [comment] 2024-08-17 03:06
Should be fixed already. Did you try the latest nightly?

**Comment by IntegerLimit** [comment] 2024-08-17 05:32
Fixed in nightly. Dupe of #898

**Closed by IntegerLimit** 2024-08-17 05:32 UTC
Labels: bug
