### ISSUE TITLE
Locked Drawers have their item removed if there is nothing in there.

### ISSUE THREAD

**Issue by Catwar234** [Nomi-CEu/Nomi-CEu#1081] opened 2024-10-17 19:59 UTC
### Nomi CEu Version

1.7.2

### Launcher

Curseforge

### Configurations or Mods Changed

None, that I remember

### Environment

Singleplayer

### Mode

Normal Mode

### What Happened

Anytime all of the items are removed from a drawer, after time the locked drawer removes its "filter." I have a subnet for my ore processing that gets dumped into drawer network, through a drawer controller. For example I have magnetite dust going into a drawer wall, then it automatically gets removed by my main net to smelt. Then when all the items get removed from the drawer the "filter" disappears no longer allowing any more magnetite dust to get put into it.

### Expected Behavior

A locked drawer should not lose it's "filtered for" item until unlocked.

### Reproduction Steps

1. Lock a drawer, then put an item into it.
2. Extract the item, so the drawer reads 0 items but still has a "filter"
3. Update the drawer block (you can probably do it by putting another item into another drawer through a drawer controller on the same "network" as the original drawer) without using a drawer key. 
4. "Filter" then get removed while the drawer is still locked

### Additional Information

(I'm not a programmer btw) Probably because the check that removes the locked "filter" on a drawer, doesn't also check if the drawer is unlocked or something.

**Comment by IntegerLimit** [comment] 2024-10-18 01:53
Fixed in Nightly. Duplicate of #1070 and other. This will be fixed in 1.7.3 as well, which will  most likely be coming in the next 12 hours.

**Closed by IntegerLimit** 2024-10-18 01:53 UTC
Labels: bug
